<template>
  <div
    class="signup-container d-flex justify-content-center align-items-center bg-light"
  >
    <div class="signup-form p-4 p-md-5 border rounded bg-white shadow-sm">
      <!-- Adjusted max-width and padding for better scaling -->
      <h2 class="h3 text-center mb-4 fw-normal">회원가입</h2>
      <!-- Simplified heading -->

      <!-- Error Message Display -->
      <div v-if="signupError" class="alert alert-danger mb-3" role="alert">
        {{ signupError }}
      </div>

      <form @submit.prevent="handleSignup">
        <!-- Nickname Input (using form-floating for consistency) -->
        <div class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            id="floatingNickname"
            placeholder="닉네임"
            v-model="formData.nickname"
            required
            :disabled="isLoading"
          />
          <label for="floatingNickname">닉네임</label>
        </div>

        <!-- Email Input (using form-floating) -->
        <div class="form-floating mb-3">
          <input
            type="email"
            class="form-control"
            id="floatingEmail"
            placeholder="name@example.com"
            v-model="formData.email"
            required
            :disabled="isLoading"
          />
          <label for="floatingEmail">이메일</label>
        </div>

        <!-- Password Input (using form-floating) -->
        <div class="form-floating mb-4 position-relative">
          <!-- Changed mb-3 to mb-4 -->
          <input
            :type="passwordFieldType"
            class="form-control pe-5"
            id="floatingPasswordSignup"
            placeholder="Password"
            v-model="formData.password"
            required
            :disabled="isLoading"
          />
          <label for="floatingPasswordSignup">비밀번호</label>
          <button
            type="button"
            @click="togglePasswordVisibility"
            class="btn btn-link position-absolute top-50 end-0 translate-middle-y me-2 border-0"
            aria-label="Toggle password visibility"
            :disabled="isLoading"
          >
            <i :class="showPassword ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
          </button>
        </div>

        <!-- Submit Button -->
        <button
          class="w-100 btn btn-lg btn-primary mb-3"
          type="submit"
          :disabled="isLoading"
        >
          <span
            v-if="isLoading"
            class="spinner-border spinner-border-sm"
            role="status"
            aria-hidden="true"
          ></span>
          <span v-else>회원가입</span>
          <!-- <i class="bi bi-arrow-right ms-auto" v-if="!isLoading"></i> Removed arrow for standard button -->
        </button>
      </form>

      <p class="mt-4 text-center text-muted small">
        이미 계정이 있으신가요?
        <a
          href="#"
          @click.prevent="goToLogin"
          class="fw-bold text-decoration-none"
          >로그인</a
        >
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue';
import { useRouter } from 'vue-router'; // Import useRouter
import axios from 'axios'; // Import axios

// --- Router Instance ---
const router = useRouter();

// --- Reactive Data ---
const formData = reactive({
  nickname: '', // Changed from name to nickname for clarity
  email: '',
  password: '',
});

const showPassword = ref(false);
const signupError = ref(null); // To store and display signup errors
const isLoading = ref(false); // To indicate loading state

// --- Computed Properties ---
const passwordFieldType = computed(() => {
  return showPassword.value ? 'text' : 'password';
});

// --- Methods ---
const togglePasswordVisibility = () => {
  showPassword.value = !showPassword.value;
};

const handleSignup = async () => {
  signupError.value = null; // Reset error on new attempt
  isLoading.value = true; // Set loading state
  console.log('Signup attempt:', formData.nickname, formData.email);

  // --- !!! SECURITY WARNING !!! ---
  // NEVER send plain text passwords to a real backend.
  // Hashing should be done server-side. This is ONLY for local json-server demo.
  // --- --- --- --- --- --- --- ---

  // Prepare the data payload for the new user
  const newUser = {
    // id: Will be auto-generated by json-server
    email: formData.email,
    password: formData.password, // INSECURE - Should be hashed
    nickname: formData.nickname,
    transactions: [], // New users start with no transactions
  };

  try {
    // Define the API endpoint (adjust if your json-server is different)
    const apiUrl = '/api/users'; // POST to the root collection

    console.log(`Checking if email exists: ${formData.email}`);
    const checkResponse = await axios.get(apiUrl, {
      params: {
        email: formData.email, // json-server filters by this parameter
      },
    });

    // If the response data array is not empty, the email exists
    if (checkResponse.data && checkResponse.data.length > 0) {
      signupError.value = '이미 사용 중인 이메일입니다.';
      isLoading.value = false;
      return; // Stop the signup process
    }

    // Send POST request using axios
    // The second argument is the data payload (request body)
    const response = await axios.post(apiUrl, newUser);

    // Check if the request was successful (axios typically considers 2xx successful)
    // json-server usually returns 201 Created
    if (response.status === 201) {
      console.log('Signup successful:', response.data);
      // --- Signup Success ---
      alert('회원가입 성공! 로그인 페이지로 이동합니다.');
      router.push('/login'); // Redirect to login page
    } else {
      // Should not happen often with basic json-server POST if data format is okay
      // but good practice to handle unexpected success codes
      console.warn('Signup completed with unexpected status:', response.status);
      signupError.value = `회원가입 완료 (상태: ${response.status}). 로그인 해보세요.`;
      router.push('/login'); // Still attempt redirect
    }
  } catch (error) {
    console.error('Signup error:', error);
    if (error.response) {
      // Server responded with a status code outside the 2xx range
      console.error('Error data:', error.response.data);
      console.error('Error status:', error.response.status);
      // Basic check - a real backend might give specific error codes (e.g., 409 for duplicate email)
      if (error.response.status === 500) {
        signupError.value =
          '서버 오류가 발생했습니다. 이메일이 이미 사용 중일 수 있습니다.';
      } else {
        signupError.value = `회원가입 중 오류가 발생했습니다 (오류 코드: ${error.response.status}).`;
      }
    } else if (error.request) {
      // Request was made but no response received
      signupError.value =
        '서버에 연결할 수 없습니다. 네트워크 또는 서버 상태를 확인하세요.';
    } else {
      // Error setting up the request
      signupError.value = '회원가입 요청 중 오류가 발생했습니다.';
    }
  } finally {
    isLoading.value = false; // Reset loading state
  }
};

// Method to navigate to login
const goToLogin = () => {
  router.push('/login');
};
</script>

<style scoped>
.signup-container {
  min-height: 80vh; /* Ensure it takes vertical space */
}

.signup-form {
  width: 100%;
  max-width: 420px; /* Consistent max-width */
  /* border: 1px solid #dee2e6; Optional border */
  border-radius: 0.375rem;
}

/* Standard button styling */
.btn-primary {
  /* Use default Bootstrap primary or customize */
}

/* Ensure input focus styles are standard */
.form-control:focus {
  border-color: #86b7fe;
  box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
}

/* Password toggle button styling */
.btn-link {
  color: #6c757d;
  text-decoration: none;
}
.btn-link:hover {
  color: #495057;
}
.btn-link:focus {
  box-shadow: none;
}

.bi {
  vertical-align: -0.125em;
}

/* Spinner styling */
.btn .spinner-border {
  margin-right: 0.5rem; /* Add space if needed */
}
</style>
